baseURL = 'https://mdgjohnny.github.io'
languageCode = 'pt-BR'
title = 'papancalypse'

theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "sobre-mim/"
  url = "sobre-mim/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "gosto-e-recomendo/"
  url = "gosto-e-recomendo/"

